
/**************************************************************
 *	
 *	crystalSound, 8 bit, 11025Hz,
 *	1 channel, 20407 bytes/channel
 *	Total Size: 1 * 20407 + 4 (header) = 20451 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\cesar\OneDrive\Documents\CesarPorcayo_FinalProject\crystalSound.wav
 *	Time-stamp: Tue Nov 28 21:08:40 2017
 *	
 **************************************************************/

#ifndef __CRYSTALSOUNDH__
#define __CRYSTALSOUNDH__

#define CRYSTALSOUNDFREQ 11025
#define CRYSTALSOUNDLEN 20407

extern const unsigned char crystalSound[20407];

#endif /* __CRYSTALSOUNDH__ */
