
/**************************************************************
 *	
 *	level3Sound, 8 bit, 11025Hz,
 *	1 channel, 2073083 bytes/channel
 *	Total Size: 1 * 2073083 + 4 (header) = 2073127 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\cesar\OneDrive\Documents\CesarPorcayo_FinalProject\level3Sound.wav
 *	Time-stamp: Tue Nov 28 21:27:40 2017
 *	
 **************************************************************/

#ifndef __LEVEL3SOUNDH__
#define __LEVEL3SOUNDH__

#define LEVEL3SOUNDFREQ 11025
#define LEVEL3SOUNDLEN 2073083

extern const unsigned char level3Sound[2073083];

#endif /* __LEVEL3SOUNDH__ */
