
/**************************************************************
 *	
 *	level2Sound, 8 bit, 11025Hz,
 *	1 channel, 1175732 bytes/channel
 *	Total Size: 1 * 1175732 + 4 (header) = 1175776 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cesar Porcayo\Documents\CS2261\CesarPorcayo_FinalProject\level2Sound.wav
 *	Time-stamp: Sat Nov 25 14:57:47 2017
 *	
 **************************************************************/

#ifndef __LEVEL2SOUNDH__
#define __LEVEL2SOUNDH__

#define LEVEL2SOUNDFREQ 11025
#define LEVEL2SOUNDLEN 1175732

extern const unsigned char level2Sound[1175732];

#endif /* __LEVEL2SOUNDH__ */
