
/**************************************************************
 *	
 *	level1Sound, 8 bit, 11025Hz,
 *	1 channel, 2069412 bytes/channel
 *	Total Size: 1 * 2069412 + 4 (header) = 2069456 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cesar Porcayo\Documents\CS2261\CesarPorcayo_FinalProject\level1Sound.wav
 *	Time-stamp: Thu Nov 23 13:23:18 2017
 *	
 **************************************************************/

#ifndef __LEVEL1SOUNDH__
#define __LEVEL1SOUNDH__

#define LEVEL1SOUNDFREQ 11025
#define LEVEL1SOUNDLEN 2069412

extern const unsigned char level1Sound[2069412];

#endif /* __LEVEL1SOUNDH__ */
