
/**************************************************************
 *	
 *	portalSound, 8 bit, 11025Hz,
 *	1 channel, 15318 bytes/channel
 *	Total Size: 1 * 15318 + 4 (header) = 15362 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cesar Porcayo\Documents\CS2261\CesarPorcayo_FinalProject\portalSound.wav
 *	Time-stamp: Sat Dec 02 11:55:46 2017
 *	
 **************************************************************/

#ifndef __PORTALSOUNDH__
#define __PORTALSOUNDH__

#define PORTALSOUNDFREQ 11025
#define PORTALSOUNDLEN 15318

extern const unsigned char portalSound[15318];

#endif /* __PORTALSOUNDH__ */
