
/**************************************************************
 *	
 *	titleSound, 8 bit, 11025Hz,
 *	1 channel, 653925 bytes/channel
 *	Total Size: 1 * 653925 + 4 (header) = 653969 bytes
 *	
 *	Generated by wav2c v1.0 from:
 *	C:\Users\Cesar Porcayo\Documents\CS2261\CesarPorcayo_FinalProject\titleSound.wav
 *	Time-stamp: Sat Nov 25 14:57:38 2017
 *	
 **************************************************************/

#ifndef __TITLESOUNDH__
#define __TITLESOUNDH__

#define TITLESOUNDFREQ 11025
#define TITLESOUNDLEN 653925

extern const unsigned char titleSound[653925];

#endif /* __TITLESOUNDH__ */
